#!/bin/bash

cp .gitignore_global ~/.gitignore_global
cp .bundle/config ~/.bundle/config

for file in $(pwd)/{.aliases,.exports,.functions,.gemrc,.pryrc,.zshrc}; do
  cp $file ~/
done

for file in $(pwd)/sublime-snippets/*.sublime-snippet; do
  cp $file /Users/justin/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Snippets/
done

for file in $(pwd)/vs-code/*.json; do
  cp $file /Users/justin/Library/Application\ Support/Code/User/
done
