#!/bin/bash

cp .zshrc ~/.zshrc
cp .gitconfig ~/.gitconfig
cp .gitignore_global ~/.gitignore_global
cp .git-commit-template ~/.git-commit-template
cp .bundle/config ~/.bundle/config

cp ~/dotfiles/vs-code/keybindings.json /Users/justin/Library/Application\ Support/Code/User

for file in $(pwd)/{.aliases,.exports,.functions,.gemrc,.irbrc,.pryrc,.rdbgrc.rb,.zshrc}; do
  cp $file ~/
done


if [ -f "$PWD/.secret_functions" ]; then
  cp $PWD/.secret_functions ~/.secret_functions
fi

# for file in $(pwd)/sublime-snippets/*.sublime-snippet; do
#   cp $file /Users/justin/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Snippets/
# done

for file in $(pwd)/vs-code/snippets/*.code-snippets; do
  cp $file /Users/justin/Library/Application\ Support/Code/User/snippets
done
