#!/bin/bash

# Sublime
cp /Users/justin/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings ~/dotfiles

# VS Code
cp /Users/justin/Library/Application\ Support/Code/User/settings.json ~/dotfiles/vs-code
cp /Users/justin/Library/Application\ Support/Code/User/keybindings.json ~/dotfiles/vs-code

for file in $(pwd)/vs-code/snippets/*.code-snippets; do
  cp $file /Users/justin/Library/Application\ Support/Code/User/snippets/
done

# keep a list of current VS Code extensions
cat ~/.vscode/extensions/extensions.json | jq > ~/dotfiles/vs-code/extensions.json

# Sync devdocs.io settings
if [[ -e ~/Downloads/devdocs.json ]]; then
  cat ~/Downloads/devdocs.json | jq > ~/dotfiles/devdocs.json
fi
